### ISSUE TITLE
Image format

### ISSUE THREAD

**Issue by egorsmkv** [shurcooL/markdownfmt#21] opened 2015-12-09 11:44 UTC
README.md

```
[![GoDoc](https://godoc.org/github.com/xenolf/lego/acme?status.svg)](https://godoc.org/github.com/xenolf/lego/acme)
[![Build Status](https://travis-ci.org/xenolf/lego.svg?branch=master)](https://travis-ci.org/xenolf/lego)
```

**markdownfmt** formatted in such a representation:

```
[![GoDoc](https://godoc.org/github.com/xenolf/lego/acme?status.svg)](https://godoc.org/github.com/xenolf/lego/acme)[![Build Status](https://travis-ci.org/xenolf/lego.svg?branch=master)](https://travis-ci.org/xenolf/lego)
```

**Comment by shurcooL** [comment] 2015-12-09 22:28
Hi @egorsmkv, thanks for reporting this.

I can explain what's happening.

Normally, `markdownftm` is configured without `EXTENSION_HARD_LINE_BREAK` option, meaning that two lines like this:

```
This is a sentence
that spans two consecutive lines.
```

Gets formatted to:

```
This is a sentence that spans two consecutive lines.
```

Rather than keeping it on 2 lines. If you want to keep the 2 lines as they are, you must add 2 spaces at the end of lines.

However, there is currently a bug, reported in #20, that causes the space between words not be added in a situation where the 2nd line contains a link.

```
text
text
```

Becomes `text text` (note the space between the two words).

But:

```
![image](url)
![image](url)
```

Becomes `![image](url)![image](url)` without a space in between two images. That's incorrect. After fixing #20, there should be a space inserted between the two images.

Since this is a duplicate of #20, I'll close, but hopefully that explains what's going on.

If you want to preserve the two images on separate lines, add 2 spaces at the end of those lines. Or put them on the same line with a space in between.

**Comment by shurcooL** [comment] 2015-12-09 22:28
Since this is a duplicate of #20, I'll close, but hopefully that explains what's going on.

If you want to preserve the two images on separate lines, add 2 spaces at the end of those lines. Or put them on the same line with a space in between.

**Closed by shurcooL** 2015-12-09 22:28 UTC
