### ISSUE TITLE
Tests failure on latest git head: Difference of 58 lines

### ISSUE THREAD

**Issue by eclipseo** [shurcooL/markdownfmt#44] opened 2018-10-26 13:08 UTC
```
Testing: "/builddir/build/BUILD/markdownfmt-5ba28a0bf0048ea9b00cecd23688dcf6cfb23fe5/_build/src/github.com/shurcooL/markdownfmt/markdown"
+ GOPATH=/builddir/build/BUILD/markdownfmt-5ba28a0bf0048ea9b00cecd23688dcf6cfb23fe5/_build:/usr/share/gocode
+ go test -buildmode pie -compiler gc -ldflags '-extldflags '\''-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\'''
--- FAIL: Test (0.00s)
    main_test.go:291: Difference of 58 lines:
        --- /tmp/markdownfmt295757931	2018-10-26 12:51:22.733756205 +0000
        +++ /tmp/markdownfmt037567182	2018-10-26 12:51:22.733756205 +0000
        @@ -152,27 +152,27 @@
         	    break;
         	```
         
        -### Blockquote within list
        +	### Blockquote within list
         
        --	list1
        +	-	list1
         
         	> This a quote within a list.
         
        -### Table within list
        +	### Table within list
         
        --	list1
        +	-	list1
         
         	| Header One | Header Two |
         	|------------|------------|
         	| Item One   | Item Two   |
         
        -### Multi-level nested
        +	### Multi-level nested
         
        --	Item 1
        +	-	Item 1
         
         	Another paragraph inside this list item is indented just like the previous paragraph.
         
        --	Item 2
        +	-	Item 2
         
         	-	Item 2a
         
        @@ -184,13 +184,13 @@
         
         	-	Item 2b
         
        --	Item 3
        +	-	Item 3
         
        -Line Breaks
        -===========
        +	Line Breaks
        +	===========
         
        -Some text with two trailing spaces for linebreak.  
        -More text immediately after.  
        -Useful for writing poems.
        +	Some text with two trailing spaces for linebreak.  
        +	More text immediately after.  
        +	Useful for writing poems.
         
        -Done.
        +	Done.
FAIL
exit status 1
FAIL	github.com/shurcooL/markdownfmt/markdown	0.012s
```

**Comment by eclipseo** [comment] 2018-10-26 13:15
The only noticeable change I made from my previous build is using Blackfriday v1.5.2.

**Comment by dmitshur** [comment] 2018-10-26 13:39
This is due to a regression in https://github.com/russross/blackfriday/pull/476. The tracking bug for it is https://github.com/russross/blackfriday/issues/495.

**Comment by dmitshur** [comment] 2019-01-26 17:07
The upstream issue russross/blackfriday#495 is fixed (thanks @aignas!), and markdownfmt tests are passing too now. Closing.

**Closed by dmitshur** 2019-01-26 17:07 UTC
Labels: external
